  inline static uintptr_t UWorld = 0x170D9D88;
    inline static uintptr_t AcknowledgedPawn = 0x350;
    inline static uintptr_t Mesh = 0x328;
    inline static uintptr_t RootComponent = 0x1B0;
    inline static uintptr_t LocalPlayers = 0x38;
    inline static uintptr_t PlayerController = 0x30;
    inline static uintptr_t OwningGameInstance = 0x200;
    inline static uintptr_t PawnPrivate = 0x320;
    inline static uintptr_t GameState = 0x188;
    inline static uintptr_t PlayerArray = 0x2c0;
    inline static uintptr_t bCanBeMarkedAsTeammate = 0x5b38;
    inline static uintptr_t CurrentWeapon = 0xA80;
    inline static uintptr_t WeaponData = 0x548;
    inline static char TeamIndex;
    inline static int KillScore = 0x1274;
    inline static uintptr_t btargetedbuild;
    inline static uintptr_t player_state = 0x2b0;
    inline static uintptr_t pawn_private = 0x320;
